feat(api): Screenshots APIs: add new parameters support
crowdin/crowdin-api-client-python pull request #141
Opened 2023-11-29 14:48 UTC by Mahhheshh

closes #139 

This PR Addes/Updates. 

The optional `labelIds` parameter has been added to `add_screenshot`. tests for adding screenshot has been updated to test the changes.

In `crowdin_api/api_resources/screenshots/types.py` the type hinting for `value` has been changed from `Any` to `str`. [docs](https://developer.crowdin.com/api/v2/#operation/api.projects.screenshots.patch)

2023-11-29 15:31 UTC, andrii-bodnar commented
Hi @Mahhheshh, could you please address the CI issues? Thanks.

2023-11-29 15:37 UTC, andrii-bodnar commented
@Mahhheshh could you please also update the [List Screenshots](https://developer.crowdin.com/api/v2/#operation/api.projects.screenshots.getMany) interface?

2023-11-29 15:45 UTC, Mahhheshh commented
Sure I will update the List Screen Shots interface also.

2023-11-29 18:25 UTC, Mahhheshh commented
It seems that I misinterpreted the documentation.

2023-11-29 19:15 UTC, andrii-bodnar requested changes

2023-11-29 19:15 UTC, andrii-bodnar commented on crowdin_api/api_resources/abstract/resources.py
> +        excludeLabelIds: Optional[Iterable[int]] = None
This is wrong, the base abstract resource shouldn't be affected. The labels are not page parameters

2023-11-29 19:15 UTC, andrii-bodnar commented on crowdin_api/api_resources/screenshots/resource.py
> +        excludeLabelIds: Optional[Iterable[int]] = None
please also add the `stringId` parameter here and put the new parameters after the `projectId`

2023-11-29 19:15 UTC, andrii-bodnar commented on crowdin_api/api_resources/screenshots/resource.py
> +                page=page, offset=offset, limit=limit, labelIds=labelIds, excludeLabelIds=excludeLabelIds),
this is not a page params, it's query params of the request

example - https://github.com/crowdin/crowdin-api-client-python/blob/main/crowdin_api/api_resources/projects/resource.py#L64

2023-11-29 19:15 UTC, andrii-bodnar commented on crowdin_api/api_resources/screenshots/resource.py
> +        labelIds: Optional[Iterable[int]] = None
please also include the other missing parameters (fileId, branchId, directoryId)

2023-11-29 19:15 UTC, andrii-bodnar commented on crowdin_api/api_resources/screenshots/resource.py
> +        if labelIds is not None:
there is no need to check if the parameter exists. Check the similar method - https://github.com/crowdin/crowdin-api-client-python/blob/main/crowdin_api/api_resources/source_files/resource.py#L193

2023-11-29 19:15 UTC, andrii-bodnar commented on crowdin_api/api_resources/screenshots/resource.py
> +                projectId=projectId, screenshotId=screenshotId),
please revert this change

2023-11-29 19:15 UTC, andrii-bodnar commented on crowdin_api/api_resources/screenshots/resource.py
> +                projectId=projectId, screenshotId=screenshotId),
and this, and below

2023-11-29 22:04 UTC, andrii-bodnar requested changes

2023-11-29 22:04 UTC, andrii-bodnar commented on crowdin_api/api_resources/screenshots/resource.py
> +        excludeLabelIds: Optional[Iterable[int]] = None
the labelIds and excludeLabelIds also put after the stringId

2023-11-29 22:04 UTC, andrii-bodnar commented on crowdin_api/api_resources/abstract/resources.py
> +from typing import Optional, Iterable
please rollback all the changes in this file

2023-11-30 07:37 UTC, andrii-bodnar approved these changes
@Mahhheshh thank you!

2023-11-30 07:38 UTC, merged