feat: add support for GraphQL endpoint
crowdin/crowdin-api-client-python pull request #189
Opened 2024-12-02 11:37 UTC by imprvhub

-Add GraphQL method to CrowdinClient for interfacing with the GraphQL endpoint.
-The implementation supports query strings and optional variables.
-Includes comprehensive test coverage for request validation.

Implements #180

2024-12-02 19:01 UTC, imprvhub commented
@andrii-bodnar PR ready for review!

2024-12-03 07:29 UTC, andrii-bodnar commented
@imprvhub thanks for the contribution!

Please add documentation about this endpoint to the Readme file.

As a reference, see the [JS API Client Readme](https://github.com/crowdin/crowdin-api-client-js?tab=readme-ov-file#graphql-api).

2024-12-03 12:53 UTC, imprvhub commented
@andrii-bodnar As requested, I have included the GraphQL API documentation in the README as part of the implementation commit [fc0648f](https://github.com/crowdin/crowdin-api-client-python/pull/189/commits/fc0648fcbb84cbc4739af4ca2b0e909f880c319d).

2024-12-03 14:39 UTC, andrii-bodnar requested changes

2024-12-03 14:39 UTC, andrii-bodnar commented on README.md
> +This library also provides possibility to use [GraphQL API](https://developer.crowdin.com/graphql-api/) (only for Crowdin Enterprise).
```suggestion
### GraphQL API

This library also provides the possibility to use [GraphQL API](https://developer.crowdin.com/graphql-api/):
```

2024-12-03 14:51 UTC, merged